### ISSUE TITLE
No awaiting reviews from me! 

### ISSUE THREAD

**Issue by boseongyun** [cfss-sp20/hw01#70]
Hello! 

I have been waiting for the reviews to be assigned to me but I haven't been able to see anything on my end yet. On the webpage, it says, "If you submitted your pull request on-time, you were randomly assigned two other pull requests to evaluate. If you did not submit your pull request on-time, you are still expected to perform two peer evaluations. Select any two pull requests and provide feedback on their submission." 

To give you more information, I completed my assignment days before the deadline and my homework case has already been closed. In this case, could you tell me if I should just go ahead and select any two pull requests?

Thank you so much!

**Comment by bensoltoff** [comment]
Your assigned peer evaluations may be for pull requests already closed by the TAs. When I or a TA finish our evaluation, we close the pull request. You can still access them by clicking the "closed" link:

![unnamed](https://user-images.githubusercontent.com/6217899/79360090-0dbaca80-7f09-11ea-8f42-8290e588ba27.png)

If you then select Reviews > Awaiting Review from You, you'll see any closed pull requests assigned to you.

**Comment by boseongyun** [comment]
Thank you so much for your reply with an awesome picture, professor Soltoff! Unfortunately, however, I still cannot see any "Awaiting review from me" in both open and closed pull requests. Could you please tell me what I should do? Perhaps, choose random 2 requests and leave reviews? 

Thank you!

**Comment by bensoltoff** [comment]
For this week, sure. Pick 2 at random

**Comment by boseongyun** [comment]
Thank you so much!
